# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JSON-XS-ByteString
version:      0.013003
version_from: lib/JSON/XS/ByteString.pm
installdirs:  site
requires:
    JSON::XS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
